(function(g){var window=this;var ODa=function(a,b){return g.Vb(a,b)},c6=function(a){g.Dn(a,"zx",g.vc());
return a},d6=function(a,b,c){g.Fa(c)||(c=[String(c)]);
g.Gn(a.o,b,c)},PDa=function(a,b){var c=[];
g.ol(b,function(a){try{var b=g.cE.prototype.A.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.za(b)?g.bE(b)&&c.push(a):c.push(a)},a);
return c},QDa=function(a,b){var c=PDa(a,b);
(0,g.C)(c,function(a){g.cE.prototype.remove.call(this,a)},a)},RDa=function(a){if(a.Nd){if(a.Nd.locationOverrideToken)return{locationOverrideToken:a.Nd.locationOverrideToken};
if(null!=a.Nd.latitudeE7&&null!=a.Nd.longitudeE7)return{latitudeE7:a.Nd.latitudeE7,longitudeE7:a.Nd.longitudeE7}}return null},SDa=function(a,b,c,d){var e=new g.un(null,void 0);
a&&g.vn(e,a);b&&g.wn(e,b);c&&g.xn(e,c);d&&g.yn(e,d);return e},e6=function(a,b){g.VE[a]=!0;
var c=g.TE();c&&c.publish.apply(c,arguments);g.VE[a]=!1},f6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.B=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.on;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",TDa(this,a.capabilities||""),UDa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",this.o=a.localChannelEncryptionKey||
"")},TDa=function(a,b){a.capabilities.clear();
(0,g.ne)(b.split(","),g.La(ODa,VDa)).forEach(function(b){a.capabilities.add(b)})},UDa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},g6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},h6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},WDa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},XDa=function(a){return new g6(a)},YDa=function(a){return g.Fa(a)?(0,g.I)(a,XDa):[]},i6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},j6=function(a){return g.Fa(a)?"["+(0,g.I)(a,i6).join(",")+"]":"null"},k6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},ZDa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},l6=function(a,b){return g.Qa(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},m6=function(a,b){return g.Qa(a,function(a){return h6(a,b)})},$Da=function(){var a=(0,g.eI)();
a&&QDa(a,a.o.de(!0))},n6=function(){var a=g.hI("yt-remote-connected-devices")||[];
g.pb(a);return a},aEa=function(a){if(g.Va(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},bEa=function(a){g.gI("yt-remote-connected-devices",a,86400)},p6=function(){if(o6)return o6;
var a=g.hI("yt-remote-device-id");a||(a=k6(),g.gI("yt-remote-device-id",a,31536E3));for(var b=n6(),c=1,d=a;g.Ua(b,d);)c++,d=a+"#"+c;return o6=d},q6=function(){var a=n6(),b=p6();
g.Ua(a,b);g.jI()&&g.rb(a,b);a=aEa(a);if(g.Va(a))try{g.EH("remote_sid")}catch(c){}else try{g.DH("remote_sid",a.join(","),-1)}catch(c){}},cEa=function(){return g.hI("yt-remote-session-browser-channel")},dEa=function(){return g.hI("yt-remote-local-screens")||[]},eEa=function(){g.gI("yt-remote-lounge-token-expiration",!0,86400)},fEa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(dEa(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.bn)(c,function(a){return!g.Ua(b,a)})&&eEa();
g.gI("yt-remote-local-screens",a,31536E3)},gEa=function(a,b){g.gI("yt-remote-session-browser-channel",a);
g.gI("yt-remote-session-screen-id",b);var c=n6(),d=p6();g.Ua(c,d)||c.push(d);bEa(c);q6()},r6=function(a){a||(g.iI("yt-remote-session-screen-id"),g.iI("yt-remote-session-video-id"));
q6();a=n6();g.Za(a,p6());bEa(a)},hEa=function(){if(!s6){var a=g.nE();
a&&(s6=new g.XD(a))}return s6?!!s6.get("yt-remote-use-staging-server"):!1},t6=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},iEa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},u6=function(a){a.length?jEa(a.shift(),function(){u6(a)}):v6()},kEa=function(a){return"chrome-extension://"+a+w6},jEa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},v6=function(){var a=iEa();
a&&a(!1,"No cast extension found")},mEa=function(){if(lEa){var a=2,b=iEa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;jEa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",v6,c)}},nEa=function(){mEa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);u6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+w6,"//www.gstatic.com/eureka/clank"+w6])},x6=function(a,b,c){g.J.call(this);
this.F=null!=c?(0,g.A)(a,c):a;this.Gd=b;this.D=(0,g.A)(this.cL,this);this.o=!1;this.A=0;this.B=this.Ia=null;this.C=[]},y6=function(){},z6=function(a,b,c,d){this.o=a;
this.B=b;this.G=c;this.F=d||1;this.C=45E3;this.Y=new g.Kn(this);this.A=new g.Og;this.A.setInterval(250)},pEa=function(a,b,c){a.Yj=1;
a.Dh=c6(b.clone());a.kj=c;a.D=!0;oEa(a,null)},A6=function(a,b,c,d,e){a.Yj=1;
a.Dh=c6(b.clone());a.kj=null;a.D=c;e&&(a.OF=!1);oEa(a,d)},oEa=function(a,b){a.Uk=(0,g.H)();
B6(a);a.fi=a.Dh.clone();d6(a.fi,"t",a.F);a.Wn=0;a.Vc=a.o.Xt(a.o.On()?b:null);0<a.Fu&&(a.Vq=new g.Xl((0,g.A)(a.fH,a,a.Vc),a.Fu));a.Y.X(a.Vc,"readystatechange",a.jV);var c=a.Ki?g.fc(a.Ki):{};a.kj?(a.Ur="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Vc.send(a.fi,a.Ur,a.kj,c)):(a.Ur="GET",a.OF&&!g.be&&(c.Connection="close"),a.Vc.send(a.fi,a.Ur,null,c));a.o.Bf(1)},sEa=function(a,b,c){for(var d=!0;!a.si&&a.Wn<c.length;){var e=qEa(a,c);
if(e==C6){4==b&&(a.Eh=4,D6(15),d=!1);break}else if(e==rEa){a.Eh=4;D6(16);d=!1;break}else E6(a,e)}4==b&&0==c.length&&(a.Eh=1,D6(17),d=!1);a.Hf=a.Hf&&d;d||(F6(a),G6(a))},qEa=function(a,b){var c=a.Wn,d=b.indexOf("\n",c);
if(-1==d)return C6;c=Number(b.substring(c,d));if(isNaN(c))return rEa;d+=1;if(d+c>b.length)return C6;var e=b.substr(d,c);a.Wn=d+c;return e},uEa=function(a,b){a.Uk=(0,g.H)();
B6(a);var c=b?window.location.hostname:"";a.fi=a.Dh.clone();g.Dn(a.fi,"DOMAIN",c);g.Dn(a.fi,"t",a.F);try{a.Jf=new ActiveXObject("htmlfile")}catch(n){F6(a);a.Eh=7;D6(22);G6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in H6)k=H6[l];else if(l in tEa)k=H6[l]=tEa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
H6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Ed(g.Sc("b/12014412"),d+"</body></html>");a.Jf.open();a.Jf.write(g.sd(c));a.Jf.close();a.Jf.parentWindow.m=(0,g.A)(a.pU,a);a.Jf.parentWindow.d=(0,g.A)(a.ZE,a,!0);a.Jf.parentWindow.rpcClose=(0,g.A)(a.ZE,a,!1);c=a.Jf.createElement("DIV");a.Jf.parentWindow.document.body.appendChild(c);d=g.fd(a.fi.toString());d=g.qc(g.cd(d));d=g.Ed(g.Sc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Ad(c,g.sd(d));a.o.Bf(1)},B6=function(a){a.wy=(0,g.H)()+
a.C;
vEa(a,a.C)},vEa=function(a,b){if(null!=a.wl)throw Error("WatchDog timer not null");
a.wl=I6((0,g.A)(a.EU,a),b)},J6=function(a){a.wl&&(g.v.clearTimeout(a.wl),a.wl=null)},G6=function(a){a.o.JB()||a.si||a.o.Eq(a)},F6=function(a){J6(a);
g.Af(a.Vq);a.Vq=null;a.A.stop();g.Qn(a.Y);if(a.Vc){var b=a.Vc;a.Vc=null;b.abort();b.dispose()}a.Jf&&(a.Jf=null)},E6=function(a,b){try{a.o.SE(a,b),a.o.Bf(4)}catch(c){}},xEa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;wEa(a,b,function(e){e?c(!0):g.v.setTimeout(function(){xEa(a,b,c,d,f)},f)})}},wEa=function(a,b,c){var d=new Image;
d.onload=function(){try{K6(d),c(!0)}catch(e){}};
d.onerror=function(){try{K6(d),c(!1)}catch(e){}};
d.onabort=function(){try{K6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{K6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},K6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},yEa=function(a){this.o=a;
this.A=new y6},zEa=function(a){var b=L6(a.o,a.Ol,"/mail/images/cleardot.gif");
c6(b);xEa(b.toString(),5E3,(0,g.A)(a.dK,a),3,2E3);a.Bf(1)},N6=function(a){var b=a.o.J;
if(null!=b)D6(5),b?(D6(11),M6(a.o,a,!1)):(D6(12),M6(a.o,a,!0));else if(a.Fe=new z6(a,void 0,void 0,void 0),a.Fe.Ki=a.Du,b=a.o,b=L6(b,b.On()?a.Fm:null,a.Eu),D6(5),!g.$d||g.Kc(10))d6(b,"TYPE","xmlhttp"),A6(a.Fe,b,!1,a.Fm,!1);else{d6(b,"TYPE","html");var c=a.Fe;a=!!a.Fm;c.Yj=3;c.Dh=c6(b.clone());uEa(c,a)}},O6=function(a,b,c){this.o=1;
this.A=[];this.C=[];this.D=new y6;this.H=a||null;this.J=null!=b?b:null;this.F=c||!1},AEa=function(a,b){this.o=a;
this.map=b;this.context=null},BEa=function(a){g.Cf.call(this,"statevent",a)},CEa=function(a,b){g.Cf.call(this,"timingevent",a);
this.size=b},DEa=function(a){g.Cf.call(this,"serverreachability",a)},GEa=function(a){EEa(a);
if(3==a.o){var b=a.wn++,c=a.gp.clone();g.Dn(c,"SID",a.B);g.Dn(c,"RID",b);g.Dn(c,"TYPE","terminate");P6(a,c);b=new z6(a,a.B,b,void 0);b.Yj=2;b.Dh=c6(c.clone());(new Image).src=b.Dh;b.Uk=(0,g.H)();B6(b)}FEa(a)},HEa=function(a){a.AK(1,0);
a.gp=L6(a,null,a.Cu);Q6(a)},EEa=function(a){a.rh&&(a.rh.abort(),a.rh=null);
a.Ac&&(a.Ac.cancel(),a.Ac=null);a.Hg&&(g.v.clearTimeout(a.Hg),a.Hg=null);R6(a);a.je&&(a.je.cancel(),a.je=null);a.xh&&(g.v.clearTimeout(a.xh),a.xh=null)},IEa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new AEa(a.bQ++,b));2!=a.o&&3!=a.o||Q6(a)},Q6=function(a){a.je||a.xh||(a.xh=I6((0,g.A)(a.YE,a),0),a.Pj=0)},KEa=function(a,b){if(1==a.o){if(!b){a.wn=Math.floor(1E5*Math.random());
var c=a.wn++,d=new z6(a,"",c,void 0);d.Ki=null;var e=S6(a),f=a.gp.clone();g.Dn(f,"RID",c);g.Dn(f,"CVER","1");P6(a,f);pEa(d,f,e);a.je=d;a.o=2}}else 3==a.o&&(b?JEa(a,b):0==a.A.length||a.je||JEa(a))},JEa=function(a,b){if(b)if(6<a.xi){a.A=a.C.concat(a.A);
a.C.length=0;var c=a.wn-1;var d=S6(a)}else c=b.G,d=b.kj;else c=a.wn++,d=S6(a);var e=a.gp.clone();g.Dn(e,"SID",a.B);g.Dn(e,"RID",c);g.Dn(e,"AID",a.uk);P6(a,e);c=new z6(a,a.B,c,a.Pj+1);c.Ki=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.je=c;pEa(c,e,d)},P6=function(a,b){if(a.Fd){var c=a.Fd.oB();
c&&g.Jb(c,function(a,c){g.Dn(b,c,a)})}},S6=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.xi&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.xi?e:f-d;try{g.Jb(k,function(a,b){c.push("req"+f+"_"+b+"="+encodeURIComponent(a))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.C=a.C.concat(a.A.splice(0,b));
return c.join("&")},LEa=function(a){a.Ac||a.Hg||(a.G=1,a.Hg=I6((0,g.A)(a.XE,a),0),a.Gj=0)},T6=function(a){if(a.Ac||a.Hg||3<=a.Gj)return!1;
a.G++;a.Hg=I6((0,g.A)(a.XE,a),MEa(a,a.Gj));a.Gj++;return!0},M6=function(a,b,c){a.Rr=c;
a.Vf=b.Ug;a.F||HEa(a)},R6=function(a){null!=a.zi&&(g.v.clearTimeout(a.zi),a.zi=null)},MEa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},U6=function(a,b){if(2==b||9==b){var c=null;
a.Fd&&(c=null);var d=(0,g.A)(a.cW,a);c||(c=new g.un("//www.google.com/images/cleardot.gif"),c6(c));wEa(c.toString(),1E4,d)}else D6(2);NEa(a,b)},NEa=function(a,b){a.o=0;
a.Fd&&a.Fd.mA(b);FEa(a);EEa(a)},FEa=function(a){a.o=0;
a.Vf=-1;if(a.Fd)if(0==a.C.length&&0==a.A.length)a.Fd.Jt();else{g.cb(a.C);var b=g.cb(a.A);a.C.length=0;a.A.length=0;a.Fd.Jt(b)}},L6=function(a,b,c){var d=g.En(c);
if(""!=d.A)b&&g.wn(d,b+"."+d.A),g.xn(d,d.D);else{var e=window.location;d=SDa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.hm&&g.Jb(a.hm,function(a,b){g.Dn(d,b,a)});
g.Dn(d,"VER",a.xi);P6(a,d);return d},I6=function(a,b){if(!g.Ha(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},D6=function(a){V6.dispatchEvent(new BEa(V6,a))},OEa=function(){},PEa=function(a,b){this.action=a;
this.params=b||{}},W6=function(a,b){g.J.call(this);
this.o=new g.U(this.fU,0,this);g.K(this,this.o);this.Gd=5E3;this.A=0;if(g.Ha(a))b&&(a=(0,g.A)(a,b));else if(a&&g.Ha(a.handleEvent))a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},X6=function(a,b,c){this.K=a;
this.F=b;this.B=new g.WD;this.A=new W6(this.GW,this);this.o=this.kb=null;this.Cb=!1;this.D=null;this.J="";this.H=this.C=0;this.G=[];this.L=c||!1},QEa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Rr,sessionId:a.o.B,arrayId:a.o.uk}},REa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&KEa(a.o),GEa(a.o));a.H=0},Y6=function(a){return!!a.o&&3==a.o.o},SEa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},Z6=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||document.location.href;var b=g.ch(a)||"";b&&(this.port=":"+b);this.domain=g.bh(a)||"";a=g.Hb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Gb(a,"10.0")&&(this.A=!1))},$6=function(a,b){var c=a.o;
if(g.za(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.lh(c+b,{})},a7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.La(a.C,d,!0),onError:g.La(a.B,e),Kd:g.La(a.D,e)};c&&(a.Sb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.BF(b,a)},WEa=function(){var a=TEa;
UEa();b7.push(a);VEa(b7)},c7=function(a,b){UEa();
var c=b7,d=XEa(a,String(b));g.Va(c)?YEa(d):(VEa(c),(0,g.C)(c,function(a){a(d)}))},UEa=function(){b7||(b7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ca("yt.mdx.remote.debug.handlers_",b7,void 0))},YEa=function(a){var b=(d7+1)%50;
d7=b;e7[b]=a;f7||(f7=49==b)},VEa=function(a){var b=e7;
if(b[0]){var c=d7,d=f7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
e7=Array(50);d7=-1;f7=!1}},XEa=function(a,b){var c=((0,g.H)()-ZEa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},g7=function(a){g.V.call(this);
this.G=a;this.o=[]},$Ea=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},aFa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.ne)(a.o,function(a){return!!l6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=$Ea(a,b[d])||c;return c},bFa=function(a,b){var c=a.o.length;
a.o=(0,g.ne)(a.o,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.o.length<c},h7=function(a,b,c,d){g.V.call(this);
this.F=a;this.D=b;this.B=c;this.C=d;this.A=0;this.o=null;this.Ia=NaN},j7=function(a){g7.call(this,"LocalScreenService");
this.B=a;this.A=NaN;i7(this);this.info("Initializing with "+j6(this.o))},cFa=function(a){if(a.o.length){var b=(0,g.I)(a.o,function(a){return a.id}),c=$6(a.B,"/pairing/get_lounge_token_batch");
a7(a.B,c,{screen_ids:b.join(",")},(0,g.A)(a.qL,a),(0,g.A)(a.pL,a))}},i7=function(a){var b=YDa(dEa());
b=(0,g.ne)(b,function(a){return!a.uuid});
return aFa(a,b)},k7=function(a,b){fEa((0,g.I)(a.o,WDa));
b&&eEa()},m7=function(a,b){g.V.call(this);
this.F=b;var c=g.hI("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Ua(c,l)}this.o=d;this.D=a;this.B=this.C=NaN;this.A=null;l7("Initialized with "+g.Ug(this.o))},dFa=function(a,b,c){var d=$6(a.D,"/pairing/get_screen_availability");
a7(a.D,d,{lounge_token:b.token},(0,g.A)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},n7=function(a,b){a:if(g.Pb(b)!=g.Pb(a.o))var c=!1;
else{c=g.Sb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(l7("Updated online screens: "+g.Ug(a.o)),a.o=b,a.V("screenChange"));eFa(a)},o7=function(a){isNaN(a.B)||g.SE(a.B);
a.B=g.QE((0,g.A)(a.rx,a),0<a.C&&a.C<(0,g.H)()?2E4:1E4)},l7=function(a){c7("OnlineScreenService",a)},fFa=function(a){var b={};
(0,g.C)(a.F(),function(a){a.token?b[a.token]=a.id:this.tc("Requesting availability of screen w/o lounge token.")});
return b},eFa=function(a){a=g.Sb(g.Kb(a.o,function(a){return a}));
g.pb(a);a.length?g.gI("yt-remote-online-screen-ids",a.join(","),60):g.iI("yt-remote-online-screen-ids")},p7=function(a){g7.call(this,"ScreenService");
this.F=a;this.A=this.B=null;this.C=[];this.D={};gFa(this)},iFa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.ze();if(k=(c?m6(k,c):null)||m6(k,b)){k.uuid=b;var l=q7(a,k);dFa(a.A,l,function(a){e(a?l:null)})}else c?hFa(a,c,(0,g.A)(function(a){var f=q7(this,new g6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));dFa(this.A,f,function(a){e(a?f:null)})},a),f):e(null)},jFa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},hFa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Sb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.BF($6(a.F,"/pairing/get_lounge_token_batch"),e)},kFa=function(a){a.o=a.B.ze();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+j6(a.o))},gFa=function(a){r7(a);
a.B=new j7(a.F);a.B.subscribe("screenChange",(0,g.A)(a.DL,a));kFa(a);a.C=YDa(g.hI("yt-remote-automatic-screen-cache")||[]);r7(a);a.info("Initializing automatic screens: "+j6(a.C));a.A=new m7(a.F,(0,g.A)(a.ze,a,!0));a.A.subscribe("screenChange",(0,g.A)(function(){this.V("onlineScreenChange")},a))},q7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=m6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.gI("yt-remote-automatic-screen-cache",(0,g.I)(a.C,WDa)));r7(a);a.D[b.uuid]=b.id;g.gI("yt-remote-device-id-map",a.D,31536E3);return b},r7=function(a){a.D=g.hI("yt-remote-device-id-map")||{}},s7=function(a,b,c){g.V.call(this);
this.R=c;this.J=a;this.A=b;this.B=null},t7=function(a,b){c7(a.R,b)},u7=function(a,b){s7.call(this,a,b,"CastSession");
this.o=null;this.C=0;this.F=(0,g.A)(this.MW,this);this.D=(0,g.A)(this.QU,this);this.C=g.QE((0,g.A)(function(){lFa(this,null)},this),12E4)},mFa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Ug(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.z,(0,g.A)(function(){t7(this,"Failed to send message: getMdxSessionStatus.")},a)):t7(a,"Sending yt message without session: "+g.Ug(b))},lFa=function(a,b){g.SE(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.B||a.B.id!=b){var c=(0,g.A)(a.Fq,a),d=(0,g.A)(a.Ee,a);a.zB(b,c,d,5)}}else a.Ee(Error("Waiting for session status timed out."))},v7=function(a,b,c){s7.call(this,a,b,"DialSession");
this.C=this.H=null;this.K="";this.N=c;this.D=null;this.G=g.z;this.F=NaN;this.L=(0,g.A)(this.PW,this);this.o=g.z},nFa=function(a){a.o=a.J.jH(a.K,a.A.label,a.A.friendlyName,(0,g.A)(function(a){this.o=g.z;
this.Fq(a)},a),(0,g.A)(function(a){this.o=g.z;
this.Ee(a)},a))},oFa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.N;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}hEa()&&(b.env_useStageMdx=1);return g.jh(b)},w7=function(a,b){s7.call(this,a,b,"ManualSession");
this.o=g.QE((0,g.A)(this.wk,this,null),150)},x7=function(a,b,c,d){g.V.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.B=[];this.C=(0,g.A)(this.oT,this)},pFa=function(a,b){return b?g.Qa(a.B,function(a){return h6(b,a.label)},a):null},y7=function(a){c7("Controller",a)},TEa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},z7=function(a){return a.D||!!a.B.length||!!a.o},A7=function(a,b,c){b!=a.o&&(g.Af(a.o),(a.o=b)?(c?a.V("yt-remote-cast2-receiver-resumed",b.A):a.V("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.A)(a.VE,a,b)),b.B?a.V("yt-remote-cast2-session-change",b.B):c&&a.o.wk(null)):a.V("yt-remote-cast2-session-change",null))},qFa=function(a){var b=a.A.iH(),c=a.o&&a.o.A;
a=(0,g.I)(b,function(a){c&&h6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=pFa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new chrome.cast.Receiver(b,a.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},wFa=function(a,b,c,d,e,f,k){rFa()?sFa(b,e,f,k)&&(C7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?tFa(a,c):(window.__onGCastApiAvailable=function(b,d){b?tFa(a,c):(D7("Failed to load cast API: "+d),E7(!1),C7(!1),g.iI("yt-remote-cast-available"),g.iI("yt-remote-cast-receiver"),uFa(),c(!1))},d?g.cF("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?nEa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?v6():(mEa(),u6(vFa.map(kEa))))):B7("Cannot initialize because not running Chrome")},uFa=function(){B7("dispose");
var a=F7();a&&a.dispose();g.Ca("yt.mdx.remote.cloudview.instance_",null,void 0);xFa(!1);g.YE(G7);G7.length=0},H7=function(){return!!g.hI("yt-remote-cast-installed")},yFa=function(){var a=g.hI("yt-remote-cast-receiver");
return a?a.friendlyName:null},zFa=function(){B7("clearCurrentReceiver");
g.iI("yt-remote-cast-receiver")},AFa=function(){return H7()?F7()?F7().getCastSession():(D7("getCastSelector: Cast is not initialized."),null):(D7("getCastSelector: Cast API is not installed!"),null)},J7=function(){H7()?F7()?I7()?(B7("Requesting cast selector."),F7().requestSession()):(B7("Wait for cast API to be ready to request the session."),G7.push(g.XE("yt-remote-cast2-api-ready",J7))):D7("requestCastSelector: Cast is not initialized."):D7("requestCastSelector: Cast API is not installed!")},K7=
function(a,b){I7()?F7().setConnectedScreenStatus(a,b):D7("setConnectedScreenStatus called before ready.")},rFa=function(){var a=0<=g.Hb.search(/ (CrMo|Chrome|CriOS)\//);
return g.FL||a},BFa=function(a,b){F7().init(a,b)},sFa=function(a,b,c,d){var e=!1;
F7()||(a=new x7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.gI("yt-remote-cast-available",a);e6("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){B7("onReceiverSelected: "+a.friendlyName);
g.gI("yt-remote-cast-receiver",a);e6("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){B7("onReceiverResumed: "+a.friendlyName);
g.gI("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){B7("onSessionChange: "+i6(a));
a||g.iI("yt-remote-cast-receiver");e6("yt-remote-cast2-session-change",a)}),g.Ca("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
B7("cloudview.createSingleton_: "+e);return e},F7=function(){return g.w("yt.mdx.remote.cloudview.instance_")},tFa=function(a,b){E7(!0);
C7(!1);BFa(a,function(a){a?(xFa(!0),g.$E("yt-remote-cast2-api-ready")):(D7("Failed to initialize cast API."),E7(!1),g.iI("yt-remote-cast-available"),g.iI("yt-remote-cast-receiver"),uFa());b(a)})},B7=function(a){c7("cloudview",a)},D7=function(a){c7("cloudview",a)},E7=function(a){B7("setCastInstalled_ "+a);
g.gI("yt-remote-cast-installed",a)},I7=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},xFa=function(a){B7("setApiReady_ "+a);
g.Ca("yt.mdx.remote.cloudview.apiReady_",a,void 0)},C7=function(a){g.Ca("yt.mdx.remote.cloudview.initializing_",a,void 0)},L7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.Zf=!1;this.J=this.H=this.A=this.C=0;this.B=NaN;this.D=!1;this.reset(a)},M7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.Zf=!1;a.hasNext=!1;a.G=0;a.F=(0,g.H)();a.C=0;a.A=0;a.H=0;a.J=0;a.B=NaN;a.D=!1},N7=function(a){return a.tb()?((0,g.H)()-a.F)/1E3:0},O7=function(a,b){a.G=b;
a.F=(0,g.H)()},P7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.H)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},Q7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&M7(a)},R7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.gc(a.o);b.hasPrevious=a.Zf;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.A;b.duration=a.H;b.loadedTime=a.J;b.liveIngestionTime=a.B;return b},T7=function(a,b){g.V.call(this);
this.o=0;this.C=a;this.F=[];this.D=new g.mD;this.B=this.A=null;this.J=(0,g.A)(this.MQ,this);this.G=(0,g.A)(this.zn,this);this.H=(0,g.A)(this.LQ,this);this.K=(0,g.A)(this.YQ,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Fy,this),CFa(this))):c=3;0!=c&&(b?this.Fy(c):g.QE((0,g.A)(function(){this.Fy(c)},this),0));
var d=AFa();d&&S7(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},U7=function(a){return new L7(a.C.getPlayerContextData())},CFa=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.F.push(this.C.subscribe(a,g.La(this.jT,a),this))},a)},DFa=function(a){(0,g.C)(a.F,function(a){this.C.unsubscribeByKey(a)},a);
a.F.length=0},V7=function(a,b){50>a.D.Kc()&&g.oD(a.D,b)},X7=function(a,b,c){var d=U7(a);
O7(d,c);-1E3!=d.playerState&&(d.playerState=b);W7(a,d)},Y7=function(a,b,c){a.C.sendMessage(b,c)},W7=function(a,b){DFa(a);
a.C.setPlayerContextData(R7(b));CFa(a)},S7=function(a,b){a.B&&(a.B.removeUpdateListener(a.J),a.B.removeMediaListener(a.G),a.zn(null));
a.B=b;a.B&&(c7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.J),a.B.addMediaListener(a.G),a.B.media.length&&a.zn(a.B.media[0]))},EFa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=U7(a);b.contentId!=d.videoId&&c7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;O7(d,a.A.getEstimatedTime());W7(a,d)}else c7("CP","No cast media video. Ignoring state update.")},Z7=function(a,b,c){return(0,g.A)(function(a){this.tc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.tc("Retrying "+b+" using MDx browser channel."),Y7(this,b,c))},a)},$7=function(a,b,c){g.V.call(this);
this.D=NaN;this.N=!1;this.K=this.J=this.L=this.R=NaN;this.T=[];this.C=this.G=this.B=this.qb=this.o=null;this.sa=a;this.T.push(g.DG(window,"beforeunload",(0,g.A)(this.gL,this)));this.A=[];this.qb=new L7;this.aa=b.id;this.o=FFa(this,c);this.o.subscribe("handlerOpened",this.QQ,this);this.o.subscribe("handlerClosed",this.NQ,this);this.o.subscribe("handlerError",this.OQ,this);this.o.subscribe("handlerMessage",this.PQ,this);SEa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var a=this.qb.videoId;
g.jI()&&g.gI("yt-remote-session-video-id",a)},this)},a8=function(a){c7("conn",a)},FFa=function(a,b){return new X6($6(a.sa,"/bc"),b)},b8=function(a,b){a.V("proxyStateChange",b)},GFa=function(a){a.D=g.QE((0,g.A)(function(){a8("Connecting timeout");
this.F(1)},a),2E4)},c8=function(a){g.SE(a.D);
a.D=NaN},d8=function(a){g.SE(a.R);
a.R=NaN},HFa=function(a){e8(a);
a.L=g.QE((0,g.A)(function(){f8(this,"getNowPlaying")},a),2E4)},e8=function(a){g.SE(a.L);
a.L=NaN},JFa=function(a,b){b&&(c8(a),d8(a));
b==(Y6(a.o)&&isNaN(a.D))?b&&(b8(a,1),f8(a,"getSubtitlesTrack")):b?(a.Z()&&a.qb.reset(),b8(a,1),f8(a,"getNowPlaying"),IFa(a)):a.F(1)},KFa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.qb.videoId&&(g.ac(b.params)?a.qb.o=null:a.qb.o=b.params,a.V("remotePlayerChange"))},LFa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.qb.listId=b.params.listId||a.qb.listId;Q7(a.qb,c,d);a.V("remoteQueueChange")},NFa=function(a,b){b.params=b.params||{};
LFa(a,b);MFa(a,b);a.V("autoplayDismissed")},MFa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
O7(a.qb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.qb.playerState&&(c=-1E3);a.qb.playerState=c;c=Number(b.params.loadedTime);a.qb.J=isNaN(c)?0:c;c=Number(b.params.duration);a.qb.H=isNaN(c)?0:c;c=a.qb;var d=Number(b.params.liveIngestionTime);c.B=d;c.D=isNaN(d)?!1:!0;c=a.qb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.A=isNaN(e)?0:e;1==a.qb.playerState?HFa(a):e8(a);a.V("remotePlayerChange")},OFa=function(a,b){if(-1E3!=
a.qb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.qb.playerState=c;c=parseInt(b.params.currentTime,10);O7(a.qb,isNaN(c)?0:c);a.V("remotePlayerChange")}},PFa=function(a,b){var c="true"==b.params.muted;
a.qb.volume=parseInt(b.params.volume,10);a.qb.muted=c;a.V("remotePlayerChange")},QFa=function(a,b){a.G=b.params.videoId;
a.V("nowAutoplaying",parseInt(b.params.timeout,10))},RFa=function(a,b){var c="true"==b.params.hasNext;
a.qb.Zf="true"==b.params.hasPrevious;a.qb.hasNext=c;a.V("previousNextChange")},IFa=function(a){g.SE(a.K);
a.K=g.QE((0,g.A)(a.F,a,1),864E5)},f8=function(a,b,c){c?a8("Sending: action="+b+", params="+g.Ug(c)):a8("Sending: action="+b);
a.o.sendMessage(b,c)},g8=function(a){g7.call(this,"ScreenServiceProxy");
this.ld=a;this.A=[];this.A.push(this.ld.$_s("screenChange",(0,g.A)(this.KW,this)));this.A.push(this.ld.$_s("onlineScreenChange",(0,g.A)(this.IS,this)))},WFa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.IE("MDX_CONFIG")||b;$Da();q6();h8||(h8=new Z6(b?b.loungeApiHost:void 0),hEa()&&(h8.o="/api/loungedev"));i8||(i8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ca("yt.mdx.remote.deferredProxies_",i8,void 0));SFa();var c=j8();if(!c){var d=new p7(h8);g.Ca("yt.mdx.remote.screenService_",d,void 0);c=j8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);wFa(a,d,function(a){a?k8()&&K7(k8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){e6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ca("yt.mdx.remote.initialized_",!0,void 0),l8("Initializing: "+g.Ug(b)),m8.push(g.XE("yt-remote-cast2-availability-change",function(){e6("yt-remote-receiver-availability-change")})),m8.push(g.XE("yt-remote-cast2-receiver-selected",function(){n8(null);
e6("yt-remote-auto-connect","cast-selector-receiver")})),m8.push(g.XE("yt-remote-cast2-receiver-resumed",function(){e6("yt-remote-receiver-resumed","cast-selector-receiver")})),m8.push(g.XE("yt-remote-cast2-session-change",TFa)),m8.push(g.XE("yt-remote-connection-change",function(a){a?K7(k8(),"YouTube TV"):o8()||(K7(null,null),zFa())})),a=p8(),b.isAuto&&(a.id+="#dial"),g.kF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),l8(" -- with channel params: "+
g.Ug(a)),UFa(a),c.start(),k8()||VFa())},YFa=function(){var a=XFa();
H7()&&g.hI("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},XFa=function(){var a=j8().ld.$_gos();
var b=q8();b&&r8()&&(l6(a,b)||a.push(b));return ZDa(a)},s8=function(){var a=ZFa();
!a&&H7()&&yFa()&&(a={key:"cast-selector-receiver",name:yFa()});return a},ZFa=function(){var a=XFa(),b=q8();
b||(b=o8());return g.Qa(a,function(a){return b&&h6(b,a.key)?!0:!1})},q8=function(){var a=k8();
if(!a)return null;var b=j8().ze();return m6(b,a)},TFa=function(a){l8("remote.onCastSessionChange_: "+i6(a));
if(a){var b=q8();b&&b.id==a.id?K7(b.id,"YouTube TV"):(b&&t8(),u8(a,1))}else r8()&&t8()},t8=function(){I7()?F7().stopSession():D7("stopSession called before API ready.");
var a=r8();a&&(a.disconnect(1),v8(null))},w8=function(){var a=r8();
return!!a&&3!=a.getProxyState()},l8=function(a){c7("remote",a)},j8=function(){if(!x8){var a=g.w("yt.mdx.remote.screenService_");
x8=a?new g8(a):null}return x8},k8=function(){return g.w("yt.mdx.remote.currentScreenId_")},$Fa=function(a){g.Ca("yt.mdx.remote.currentScreenId_",a,void 0)},aGa=function(){return g.w("yt.mdx.remote.connectData_")},n8=function(a){g.Ca("yt.mdx.remote.connectData_",a,void 0)},r8=function(){return g.w("yt.mdx.remote.connection_")},v8=function(a){var b=r8();
n8(null);a||$Fa("");g.Ca("yt.mdx.remote.connection_",a,void 0);i8&&((0,g.C)(i8,function(b){b(a)}),i8.length=0);
b&&!a?e6("yt-remote-connection-change",!1):!b&&a&&e6("yt-remote-connection-change",!0)},o8=function(){var a=g.jI();
if(!a)return null;var b=j8().ze();return m6(b,a)},u8=function(a,b){q8()&&q8();
$Fa(a.id);var c=new $7(h8,a,p8());c.connect(b,aGa());c.subscribe("beforeDisconnect",function(a){e6("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){r8()&&v8(null)});
v8(c)},VFa=function(){var a=o8();
a?(l8("Resume connection to: "+i6(a)),u8(a,0)):(r6(),zFa(),l8("Skipping connecting because no session screen found."))},SFa=function(){var a=p8();
if(g.ac(a)){a=p6();var b=g.hI("yt-remote-session-name")||"",c=g.hI("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ca("yt.mdx.remote.channelParams_",a,void 0)}},p8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},UFa=function(a){a?(g.gI("yt-remote-session-app",a.app),g.gI("yt-remote-session-name",a.name)):(g.iI("yt-remote-session-app"),g.iI("yt-remote-session-name"));
g.Ca("yt.mdx.remote.channelParams_",a,void 0)},y8=function(a,b,c){g.J.call(this);
this.D=a;this.A=b;this.B=new g.SG(this);g.K(this,this.B);this.B.O(b,"onCaptionsTrackListChanged",this.cS);this.B.O(b,"captionschanged",this.KQ);this.B.O(b,"captionssettingschanged",this.wG);this.B.O(b,"videoplayerreset",this.Gq);this.B.O(b,"mdxautoplaycancel",this.cK);this.T=this.B.O(b,"onVolumeChange",this.CE);this.H=!1;this.o=c;c.subscribe("proxyStateChange",this.RE,this);c.subscribe("remotePlayerChange",this.Cn,this);c.subscribe("remoteQueueChange",this.Gq,this);c.subscribe("autoplayUpNext",this.oE,
this);c.subscribe("previousNextChange",this.OE,this);c.subscribe("nowAutoplaying",this.GE,this);c.subscribe("autoplayDismissed",this.nE,this);this.suggestion=null;this.J=new g.MQ(64);this.C=new g.U(this.tG,500,this);g.K(this,this.C);this.F=new g.U(this.uG,1E3,this);g.K(this,this.F);this.L=new x6(this.mW,0,this);g.K(this,this.L);this.G={};this.R=new g.U(this.WG,1E3,this);g.K(this,this.R);this.K=new g.Xl(this.EO,1E3,this);g.K(this,this.K);this.N=g.z;this.wG();this.Gq();this.Cn()},z8=function(a,b){a.D.Je(b,
a.A.getVideoData().lengthSeconds)},bGa=function(a){z8(a,0);
a.C.stop();A8(a,new g.MQ(64))},C8=function(a,b){if(B8(a)&&!a.H){var c=null;
b&&(c={style:a.A.getSubtitlesUserSettings()},g.ic(c,b));a.o.gG(a.A.getVideoData(1).videoId,c);a.G=U7(a.o).o}},D8=function(a,b){var c=a.A.getPlaylist();
if(c){var d=c.ye();var e=c.listId.toString()}c=a.A.getVideoData(1);a.o.playVideo(c.videoId,b,d,e,c.playerParams,c.jk,RDa(c));A8(a,new g.MQ(1))},cGa=function(a,b){if(b){var c=a.A.getOption("captions","tracklist",{K4:1});
c&&c.length?(a.A.setOption("captions","track",b),a.H=!1):(a.A.loadModule("captions"),a.H=!0)}else a.A.setOption("captions","track",{})},B8=function(a){return U7(a.o).videoId==a.A.getVideoData(1).videoId},A8=function(a,b){a.F.stop();
var c=a.J;if(!g.SQ(c,b)){var d=g.X(b,2);d!=g.X(a.J,2)&&g.VU(a.A,d);a.J=b;dGa(a.D,c,b)}},E8=function(a){g.W.call(this,{I:"div",
M:"ytp-remote",P:[{I:"div",M:"ytp-remote-display-status",P:[{I:"div",M:"ytp-remote-display-status-icon",P:[g.vsa()]},{I:"div",M:"ytp-remote-display-status-text",ba:"{{statustext}}"}]}]});this.B=new g.MV(this,250);g.K(this,this.B);this.C=a;this.O(a,"presentingplayerstatechange",this.D);eGa(this,g.RU(a))},eGa=function(a,b){if(3==a.C.getPresentingPlayerType()){var c={RECEIVER_NAME:a.C.getOption("remote","currentReceiver").name};
c=g.X(b,128)?g.EV("No se ha podido reproducir el v\u00eddeo en $RECEIVER_NAME",c):b.tb()||g.X(b,4)?g.EV("El v\u00eddeo se est\u00e1 reproduciendo en $RECEIVER_NAME",c):g.EV("Conectado a $RECEIVER_NAME",c);a.updateValue("statustext",c);a.B.show()}else a.B.hide()},F8=function(a,b){g.cX.call(this,"Reproducir en",0,a,b);
this.B=a;this.H={};this.O(a,"onMdxReceiversChange",this.L);this.O(a,"presentingplayerstatechange",this.L);this.L()},G8=function(a){g.oV.call(this,a);
this.A={key:k6(),name:"Este ordenador"};this.C=null;this.D=[];this.G=this.o=null;this.F=[this.A];this.B=this.A;this.kn=new g.MQ(64);this.J=0;this.H=-1;if(!g.EN(g.Y(this.player))){a=this.player;var b=g.BQ(a);b&&(b=b.mn())&&(b=new F8(a,b),g.K(this,b));b=new E8(a);g.K(this,b);g.fV(a,b.element,4)}},dGa=function(a,b,c){a.kn=c;
a.player.V("presentingplayerstatechange",new g.WQ(c,b))},H8=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)t8();
else{a.B=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Ga(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.jk,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(d=RDa(d))&&(c.locationInfo=d);d=c}else d=null;l8("Connecting to: "+g.Ug(b));"cast-selector-receiver"==b.key?
(n8(d||null),I7()?F7().setLaunchParams(d||null):D7("setLaunchParams called before ready.")):!d&&w8()&&k8()==b.key?e6("yt-remote-connection-change",!0):(t8(),n8(d||null),d=j8().ze(),(d=m6(d,b.key))&&u8(d,1))}},tEa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},H6={"'":"\\'"},fGa={},VDa={iY:"atp",N2:"ska",b2:"que",m1:"mus",J2:"sus",v_:"dsp",t2:"seq"};
f6.prototype.sh=function(){var a=new f6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.B=this.B;a.A=this.A;a.o=this.o};
var s6,o6="",w6=t6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",lEa=t6("loadCastFramework")||t6("loadCastApplicationFramework"),vFa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.B(x6,g.J);g.h=x6.prototype;g.h.bL=function(a){this.C=arguments;this.o=!1;this.Ia?this.B=(0,g.H)()+this.Gd:this.Ia=g.Pg(this.D,this.Gd)};
g.h.stop=function(){this.Ia&&(g.Qg(this.Ia),this.Ia=null);this.B=null;this.o=!1;this.C=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.C)))};
g.h.W=function(){this.stop();x6.ga.W.call(this)};
g.h.cL=function(){this.B?(this.Ia=g.Pg(this.D,this.B-(0,g.H)()),this.B=null):(this.Ia=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.C)))};y6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};g.h=z6.prototype;g.h.Ki=null;g.h.Hf=!1;g.h.wl=null;g.h.wy=null;g.h.Uk=null;g.h.Yj=null;g.h.Dh=null;g.h.fi=null;g.h.kj=null;g.h.Vc=null;g.h.Wn=0;g.h.Jf=null;g.h.Ur=null;g.h.Eh=null;g.h.Gm=-1;g.h.OF=!0;g.h.si=!1;g.h.Fu=0;g.h.Vq=null;var rEa={},C6={};g.h=z6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.jV=function(a){a=a.target;var b=this.Vq;b&&3==g.hy(a)?b.Cm():this.fH(a)};
g.h.fH=function(a){try{if(a==this.Vc)a:{var b=g.hy(this.Vc),c=this.Vc.A,d=this.Vc.getStatus();if(g.$d&&!g.Kc(10)||g.be&&!g.Jc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Ef&&!g.ly(this.Vc))break a;this.si||4!=b||7==c||(8==c||0>=d?this.o.Bf(3):this.o.Bf(2));J6(this);var e=this.Vc.getStatus();this.Gm=e;var f=g.ly(this.Vc);(this.Hf=200==e)?(4==b&&F6(this),this.D?(sEa(this,b,f),g.Ef&&this.Hf&&3==b&&(this.Y.X(this.A,"tick",this.eV),this.A.start())):E6(this,f),this.Hf&&!this.si&&(4==b?this.o.Eq(this):
(this.Hf=!1,B6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Eh=3,D6(13)):(this.Eh=0,D6(14)),F6(this),G6(this))}}catch(k){this.Vc&&g.ly(this.Vc)}finally{}};
g.h.eV=function(){var a=g.hy(this.Vc),b=g.ly(this.Vc);this.Wn<b.length&&(J6(this),sEa(this,a,b),this.Hf&&4!=a&&B6(this))};
g.h.pU=function(a){I6((0,g.A)(this.oU,this,a),0)};
g.h.oU=function(a){this.si||(J6(this),E6(this,a),B6(this))};
g.h.ZE=function(a){I6((0,g.A)(this.nU,this,a),0)};
g.h.nU=function(a){this.si||(F6(this),this.Hf=a,this.o.Eq(this),this.o.Bf(4))};
g.h.cancel=function(){this.si=!0;F6(this)};
g.h.EU=function(){this.wl=null;var a=(0,g.H)();0<=a-this.wy?(2!=this.Yj&&this.o.Bf(3),F6(this),this.Eh=2,D6(18),G6(this)):vEa(this,this.wy-a)};
g.h.getLastError=function(){return this.Eh};g.h=yEa.prototype;g.h.Du=null;g.h.Fe=null;g.h.Wq=!1;g.h.KB=null;g.h.ep=null;g.h.Jv=null;g.h.Eu=null;g.h.Ze=null;g.h.Ug=-1;g.h.Fm=null;g.h.Ol=null;g.h.connect=function(a){this.Eu=a;a=L6(this.o,null,this.Eu);D6(3);this.KB=(0,g.H)();var b=this.o.H;null!=b?(this.Fm=b[0],(this.Ol=b[1])?(this.Ze=1,zEa(this)):(this.Ze=2,N6(this))):(d6(a,"MODE","init"),this.Fe=new z6(this,void 0,void 0,void 0),this.Fe.Ki=this.Du,A6(this.Fe,a,!1,null,!0),this.Ze=0)};
g.h.dK=function(a){if(a)this.Ze=2,N6(this);else{D6(4);var b=this.o;b.Vf=b.rh.Ug;U6(b,9)}a&&this.Bf(2)};
g.h.Xt=function(a){return this.o.Xt(a)};
g.h.abort=function(){this.Fe&&(this.Fe.cancel(),this.Fe=null);this.Ug=-1};
g.h.JB=function(){return!1};
g.h.SE=function(a,b){this.Ug=a.Gm;if(0==this.Ze)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.Vf=this.Ug;U6(c,2);return}this.Fm=c[0];this.Ol=c[1]}else c=this.o,c.Vf=this.Ug,U6(c,2);else if(2==this.Ze)if(this.Wq)D6(7),this.Jv=(0,g.H)();else if("11111"==b){if(D6(6),this.Wq=!0,this.ep=(0,g.H)(),c=this.ep-this.KB,!g.$d||g.Kc(10)||500>c)this.Ug=200,this.Fe.cancel(),D6(12),M6(this.o,this,!0)}else D6(8),this.ep=this.Jv=(0,g.H)(),this.Wq=!1};
g.h.Eq=function(){this.Ug=this.Fe.Gm;if(this.Fe.Hf)0==this.Ze?this.Ol?(this.Ze=1,zEa(this)):(this.Ze=2,N6(this)):2==this.Ze&&((!g.$d||g.Kc(10)?!this.Wq:200>this.Jv-this.ep)?(D6(11),M6(this.o,this,!1)):(D6(12),M6(this.o,this,!0)));else{0==this.Ze?D6(9):2==this.Ze&&D6(10);var a=this.o;a.Vf=this.Ug;U6(a,2)}};
g.h.On=function(){return this.o.On()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Bf=function(a){this.o.Bf(a)};g.h=O6.prototype;g.h.hm=null;g.h.je=null;g.h.Ac=null;g.h.Cu=null;g.h.gp=null;g.h.bA=null;g.h.xp=null;g.h.wn=0;g.h.bQ=0;g.h.Fd=null;g.h.xh=null;g.h.Hg=null;g.h.zi=null;g.h.rh=null;g.h.Rr=null;g.h.uk=-1;g.h.BC=-1;g.h.Vf=-1;g.h.Pj=0;g.h.Gj=0;g.h.xi=8;var V6=new g.dg;g.B(BEa,g.Cf);g.B(CEa,g.Cf);g.B(DEa,g.Cf);g.h=O6.prototype;g.h.connect=function(a,b,c,d,e){D6(0);this.Cu=b;this.hm=c||{};d&&g.za(e)&&(this.hm.OSID=d,this.hm.OAID=e);this.F?(I6((0,g.A)(this.uA,this,a),100),HEa(this)):this.uA(a)};
g.h.uA=function(a){this.rh=new yEa(this);this.rh.Du=null;this.rh.A=this.D;this.rh.connect(a)};
g.h.JB=function(){return 0==this.o};
g.h.YE=function(a){this.xh=null;KEa(this,a)};
g.h.XE=function(){this.Hg=null;this.Ac=new z6(this,this.B,"rpc",this.G);this.Ac.Ki=null;this.Ac.Fu=0;var a=this.bA.clone();g.Dn(a,"RID","rpc");g.Dn(a,"SID",this.B);g.Dn(a,"CI",this.Rr?"0":"1");g.Dn(a,"AID",this.uk);P6(this,a);if(!g.$d||g.Kc(10))g.Dn(a,"TYPE","xmlhttp"),A6(this.Ac,a,!0,this.xp,!1);else{g.Dn(a,"TYPE","html");var b=this.Ac,c=!!this.xp;b.Yj=3;b.Dh=c6(a.clone());uEa(b,c)}};
g.h.SE=function(a,b){if(0!=this.o&&(this.Ac==a||this.je==a))if(this.Vf=a.Gm,this.je==a&&3==this.o)if(7<this.xi){try{var c=this.D.parse(b)}catch(f){c=null}if(g.Fa(c)&&3==c.length)if(0==c[0])a:{if(!this.Hg){if(this.Ac)if(this.Ac.Uk+3E3<this.je.Uk)R6(this),this.Ac.cancel(),this.Ac=null;else break a;T6(this);D6(19)}}else this.BC=c[1],0<this.BC-this.uk&&37500>c[2]&&this.Rr&&0==this.Gj&&!this.zi&&(this.zi=I6((0,g.A)(this.FQ,this),6E3));else U6(this,11)}else b!=fGa.mZ.o&&U6(this,11);else if(this.Ac==a&&
R6(this),!g.D(b)){c=this.D.parse(b);g.Fa(c);for(var d=0;d<c.length;d++){var e=c[d];this.uk=e[0];e=e[1];2==this.o?"c"==e[0]?(this.B=e[1],this.xp=e[2],e=e[3],null!=e?this.xi=e:this.xi=6,this.o=3,this.Fd&&this.Fd.oA(),this.bA=L6(this,this.On()?this.xp:null,this.Cu),LEa(this)):"stop"==e[0]&&U6(this,7):3==this.o&&("stop"==e[0]?U6(this,7):"noop"!=e[0]&&this.Fd&&this.Fd.nA(e),this.Gj=0)}}};
g.h.FQ=function(){null!=this.zi&&(this.zi=null,this.Ac.cancel(),this.Ac=null,T6(this),D6(20))};
g.h.Eq=function(a){if(this.Ac==a){R6(this);this.Ac=null;var b=2}else if(this.je==a)this.je=null,b=1;else return;this.Vf=a.Gm;if(0!=this.o)if(a.Hf)1==b?(b=(0,g.H)()-a.Uk,V6.dispatchEvent(new CEa(V6,a.kj?a.kj.length:0,b,this.Pj)),Q6(this),this.C.length=0):LEa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Vf)){if(d=1==b)this.je||this.xh||1==this.o||2<=this.Pj?d=!1:(this.xh=I6((0,g.A)(this.YE,this,a),MEa(this,this.Pj)),this.Pj++,d=!0);d=!(d||2==b&&T6(this))}if(d)switch(c){case 1:U6(this,
5);break;case 4:U6(this,10);break;case 3:U6(this,6);break;case 7:U6(this,12);break;default:U6(this,2)}}};
g.h.AK=function(a){if(!g.Ua(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.cW=function(a){a?D6(2):(D6(1),NEa(this,8))};
g.h.Xt=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.by;a.H=!1;return a};
g.h.isActive=function(){return!!this.Fd&&this.Fd.isActive(this)};
g.h.Bf=function(a){V6.dispatchEvent(new DEa(V6,a))};
g.h.On=function(){return!(!g.$d||g.Kc(10))};
g.h=OEa.prototype;g.h.oA=function(){};
g.h.nA=function(){};
g.h.mA=function(){};
g.h.Jt=function(){};
g.h.oB=function(){return{}};
g.h.isActive=function(){return!0};g.B(W6,g.J);g.h=W6.prototype;g.h.fU=function(){this.Gd=Math.min(3E5,2*this.Gd);this.B();this.A&&this.start()};
g.h.start=function(){var a=this.Gd+15E3*Math.random();g.av(this.o,a);this.A=(0,g.H)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Gd=5E3};g.B(X6,OEa);g.h=X6.prototype;g.h.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.h.Ak=function(a){return this.B.Li(a)};
g.h.V=function(a,b){return this.B.V.apply(this.B,arguments)};
g.h.dispose=function(){this.Cb||(this.Cb=!0,g.Af(this.B),REa(this),g.Af(this.A),this.A=null)};
g.h.la=function(){return this.Cb};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.A.stop();this.D=a||null;this.C=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new O6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.L),e=this.o;e&&(e.Fd=null);d.Fd=this;this.o=d;e?this.o.connect(a,b,this.F,e.B,e.uk):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ic(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):Y6(this)&&IEa(this.o,c)};
g.h.oA=function(){this.A.reset();this.D=null;this.C=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)IEa(this.o,a[b])}this.V("handlerOpened")};
g.h.mA=function(a){var b=2==a&&401==this.o.Vf;4==a||b||this.A.start();this.V("handlerError",a)};
g.h.Jt=function(a){if(!this.A.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.oB=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.C&&(a.ui=""+this.C);0!=this.H&&(a.ui=""+this.H);this.D&&g.ic(a,this.D);return a};
g.h.nA=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),GEa(this.o)):this.V("handlerMessage",new PEa(a[0],a[1]))};
g.h.GW=function(){this.A.isActive();var a=this.o,b=0;a.Ac&&b++;a.je&&b++;0!=b||this.connect(this.D,this.C)};Z6.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
Z6.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
Z6.prototype.D=function(a){a(Error("request timed out"))};var ZEa=(0,g.H)(),b7=null,e7=Array(50),d7=-1,f7=!1;g.B(g7,g.V);g7.prototype.ze=function(){return this.o};
g7.prototype.contains=function(a){return!!l6(this.o,a)};
g7.prototype.get=function(a){return a?m6(this.o,a):null};
g7.prototype.info=function(a){c7(this.G,a)};g.B(h7,g.V);var gGa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=h7.prototype;g.h.start=function(){!this.o&&isNaN(this.Ia)&&this.hH()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ia)||(g.SE(this.Ia),this.Ia=NaN)};
g.h.W=function(){this.stop();h7.ga.W.call(this)};
g.h.hH=function(){this.Ia=NaN;this.o=g.BF($6(this.F,"/pairing/get_screen"),{method:"POST",Sb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.A)(this.IW,this),onError:(0,g.A)(this.HW,this),Kd:(0,g.A)(this.JW,this)})};
g.h.IW=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.V("pairingComplete",new g6(c))};
g.h.HW=function(a){this.o=null;a.status&&404==a.status?this.A>=gGa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=gGa[this.A],this.Ia=g.QE((0,g.A)(this.hH,this),a),this.A++):this.V("pairingFailed",Error("Server error "+a.status))};
g.h.JW=function(){this.o=null;this.V("pairingFailed",Error("Server not responding"))};g.B(j7,g7);g.h=j7.prototype;g.h.start=function(){i7(this)&&this.V("screenChange");!g.hI("yt-remote-lounge-token-expiration")&&cFa(this);g.SE(this.A);this.A=g.QE((0,g.A)(this.start,this),1E4)};
g.h.add=function(a,b){i7(this);$Ea(this,a);k7(this,!1);this.V("screenChange");b(a);a.token||cFa(this)};
g.h.remove=function(a,b){var c=i7(this);bFa(this,a)&&(k7(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.h.Nr=function(a,b,c,d){var e=i7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,k7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.h.W=function(){g.SE(this.A);j7.ga.W.call(this)};
g.h.qL=function(a){i7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}k7(this,!b);b&&c7(this.G,"Missed "+b+" lounge tokens.")};
g.h.pL=function(a){c7(this.G,"Requesting lounge tokens failed: "+a)};g.B(m7,g.V);g.h=m7.prototype;g.h.start=function(){var a=parseInt(g.hI("yt-remote-fast-check-period")||"0",10);(this.C=(0,g.H)()-144E5<a?0:a)?o7(this):(this.C=(0,g.H)()+3E5,g.gI("yt-remote-fast-check-period",this.C),this.rx())};
g.h.isEmpty=function(){return g.ac(this.o)};
g.h.update=function(){l7("Updating availability on schedule.");var a=this.F(),b=g.Kb(this.o,function(b,d){return b&&!!m6(a,d)},this);
n7(this,b)};
g.h.W=function(){g.SE(this.B);this.B=NaN;this.A&&(this.A.abort(),this.A=null);m7.ga.W.call(this)};
g.h.rx=function(){g.SE(this.B);this.B=NaN;this.A&&this.A.abort();var a=fFa(this);if(g.Pb(a)){var b=$6(this.D,"/pairing/get_screen_availability");this.A=a7(this.D,b,{lounge_token:g.Sb(a).join(",")},(0,g.A)(this.KT,this,a),(0,g.A)(this.JT,this))}else n7(this,{}),o7(this)};
g.h.KT=function(a,b){this.A=null;var c=g.Sb(fFa(this));if(g.qb(c,g.Sb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;n7(this,d);o7(this)}else this.tc("Changing Screen set during request."),this.rx()};
g.h.JT=function(a){this.tc("Screen availability failed: "+a);this.A=null;o7(this)};
g.h.tc=function(a){c7("OnlineScreenService",a)};g.B(p7,g7);g.h=p7.prototype;g.h.start=function(){this.B.start();this.A.start();this.o.length&&(this.V("screenChange"),this.A.isEmpty()||this.V("onlineScreenChange"))};
g.h.add=function(a,b,c){this.B.add(a,b,c)};
g.h.remove=function(a,b,c){this.B.remove(a,b,c);this.A.update()};
g.h.Nr=function(a,b,c,d){this.B.contains(a)?this.B.Nr(a,b,c,d):(a="Updating name of unknown screen: "+a.name,c7(this.G,a),d(Error(a)))};
g.h.ze=function(a){return a?this.o:g.bb(this.o,(0,g.ne)(this.C,function(a){return!this.contains(a)},this))};
g.h.iH=function(){return(0,g.ne)(this.ze(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.jH=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new h7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(a){g.Af(f);d(q7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.Af(f);e(a)});
f.start();return(0,g.A)(f.stop,f)};
g.h.LW=function(a,b,c,d){g.BF($6(this.F,"/pairing/get_screen"),{method:"POST",Sb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.A)(function(a,d){var e=new g6(d.screen||{});if(!e.name||jFa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);jFa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(q7(this,e))},this),
onError:(0,g.A)(function(a){d(Error("pairing request failed: "+a.status))},this),
Kd:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.h.W=function(){g.Af(this.B);g.Af(this.A);p7.ga.W.call(this)};
g.h.DL=function(){kFa(this);this.V("screenChange");this.A.update()};
p7.prototype.dispose=p7.prototype.dispose;g.B(s7,g.V);g.h=s7.prototype;g.h.Fq=function(a){this.B=a;this.V("sessionScreen",this.B)};
g.h.Ee=function(a){this.la()||(a&&t7(this,""+a),this.B=null,this.V("sessionScreen",null))};
g.h.info=function(a){c7(this.R,a)};
g.h.lH=function(){return null};
g.h.Fx=function(a){var b=this.A;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){t7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.W=function(){this.Fx("");s7.ga.W.call(this)};g.B(u7,s7);g.h=u7.prototype;g.h.Ex=function(a){if(this.o){if(this.o==a)return;t7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);mFa(this)};
g.h.wk=function(a){this.info("launchWithParams no-op for Cast: "+g.Ug(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.A)(function(){this.Ee()},this),(0,g.A)(function(){this.Ee(Error("Failed to stop receiver app."))},this)):this.Ee(Error("Stopping cast device witout session."))};
g.h.Fx=g.z;g.h.W=function(){this.info("disposeInternal");g.SE(this.C);this.C=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;u7.ga.W.call(this)};
g.h.QU=function(a,b){if(!this.la())if(b){var c=g.Xx(b);if(g.Ia(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Ug(c));switch(d){case "mdxSessionStatus":lFa(this,c.screenId);break;default:t7(this,"Unknown youtube message: "+d)}}else t7(this,"Unable to parse message.")}else t7(this,"No data in message.")};
g.h.zB=function(a,b,c,d){iFa(this.J,this.A.label,a,this.A.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(t7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.QE((0,g.A)(this.zB,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.lH=function(){return this.o};
g.h.MW=function(a){this.la()||a||(t7(this,"Cast session died."),this.Ee())};g.B(v7,s7);g.h=v7.prototype;g.h.Ex=function(a){this.C=a;this.C.addUpdateListener(this.L)};
g.h.wk=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.z;g.SE(this.F);this.C?this.C.stop((0,g.A)(this.Ee,this,null),(0,g.A)(this.Ee,this,"Failed to stop DIAL device.")):this.Ee()};
g.h.W=function(){this.o();this.o=g.z;g.SE(this.F);this.C&&this.C.removeUpdateListener(this.L);this.C=null;v7.ga.W.call(this)};
g.h.PW=function(a){this.la()||a||(t7(this,"DIAL session died."),this.o(),this.o=g.z,this.Ee())};
g.h.gv=function(a){this.K=k6();if(this.D){var b=new chrome.cast.DialLaunchResponse(!0,oFa(this));a(b);nFa(this)}else this.G=(0,g.A)(function(){g.SE(this.F);this.G=g.z;this.F=NaN;var b=new chrome.cast.DialLaunchResponse(!0,oFa(this));a(b);nFa(this)},this),this.F=g.QE((0,g.A)(function(){this.G()},this),100)};
g.h.QM=function(a,b,c){iFa(this.J,this.H.receiver.label,a,this.A.friendlyName,(0,g.A)(function(a){a&&a.token?(this.Fq(a),b(new chrome.cast.DialLaunchResponse(!1))):this.gv(b,c)},this),(0,g.A)(function(a){t7(this,"Failed to get DIAL screen: "+a);
this.gv(b,c)},this))};g.B(w7,s7);w7.prototype.stop=function(){this.Ee()};
w7.prototype.Ex=g.z;w7.prototype.wk=function(){g.SE(this.o);this.o=NaN;var a=m6(this.J.ze(),this.A.label);a?this.Fq(a):this.Ee(Error("No such screen"))};
w7.prototype.W=function(){g.SE(this.o);this.o=NaN;w7.ga.W.call(this)};g.B(x7,g.V);g.h=x7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new chrome.cast.ApiConfig(c,(0,g.A)(this.UE,this),(0,g.A)(this.sT,this),d,e);c.customDialLaunchCallback=(0,g.A)(this.nR,this);chrome.cast.initialize(c,(0,g.A)(function(){this.la()||
(chrome.cast.addReceiverActionListener(this.C),WEa(),this.A.subscribe("onlineScreenChange",(0,g.A)(this.kH,this)),this.B=qFa(this),chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(a){this.tc("Failed to set initial custom receivers: "+g.Ug(a))},this)),this.V("yt-remote-cast2-availability-change",z7(this)),b(!0))},this),(0,g.A)(function(a){this.tc("Failed to initialize API: "+g.Ug(a));
b(!1)},this))};
g.h.KV=function(a,b){y7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.B;if(!a||c&&c.id!=a)y7("Unsetting old screen status: "+this.o.A.friendlyName),A7(this,null)}if(a&&b){if(!this.o){c=m6(this.A.ze(),a);if(!c){y7("setConnectedScreenStatus: Unknown screen.");return}var d=pFa(this,c);d||(y7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.B.push(d),chrome.cast.setCustomReceivers(this.B,
g.z,(0,g.A)(function(a){this.tc("Failed to set initial custom receivers: "+g.Ug(a))},this)));
y7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);A7(this,new w7(this.A,d),!0)}this.o.Fx(b)}else y7("setConnectedScreenStatus: no screen.")};
g.h.LV=function(a){this.la()?this.tc("Setting connection data on disposed cast v2"):this.o?this.o.wk(a):this.tc("Setting connection data without a session")};
g.h.OW=function(){this.la()?this.tc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),A7(this,null)):y7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.A)(this.UE,this),(0,g.A)(this.PT,this))};
g.h.W=function(){this.A.unsubscribe("onlineScreenChange",(0,g.A)(this.kH,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.C);g.Za(g.w("yt.mdx.remote.debug.handlers_")||[],TEa);g.Af(this.o);x7.ga.W.call(this)};
g.h.tc=function(a){c7("Controller",a)};
g.h.VE=function(a,b){this.o==a&&(b||A7(this,null),this.V("yt-remote-cast2-session-change",b))};
g.h.oT=function(a,b){if(!this.la())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),y7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)y7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{y7("onReceiverAction_: Casting to active receiver.");this.o.B&&this.V("yt-remote-cast2-session-change",this.o.B);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:A7(this,
new w7(this.A,a));break;case chrome.cast.ReceiverType.DIAL:A7(this,new v7(this.A,a,this.F));break;case chrome.cast.ReceiverType.CAST:A7(this,new u7(this.A,a));break;default:this.tc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.tc("Stopping receiver w/o session: "+a.friendlyName)}else this.tc("onReceiverAction_ called without receiver.")};
g.h.nR=function(a){if(this.la())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.tc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.tc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.B)return y7("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.o.B),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.tc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);A7(this,new v7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.A)(b.QM,b,(b.H.extraData||{}).screenId||null)):new Promise((0,g.A)(b.gv,b))};
g.h.UE=function(a){if(!this.la()){y7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)y7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),A7(this,new u7(this.A,b),!0);else{this.tc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=m6(this.A.ze(),c.label);d&&h6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(y7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Af(this.o),this.o=new u7(this.A,b),this.o.subscribe("sessionScreen",(0,g.A)(this.VE,this,this.o)),this.o.wk(null));this.o.Ex(a)}}};
g.h.NW=function(){return this.o?this.o.lH():null};
g.h.PT=function(a){this.la()||(this.tc("Failed to estabilish a session: "+g.Ug(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&A7(this,null))};
g.h.sT=function(a){y7("Receiver availability updated: "+a);if(!this.la()){var b=z7(this);this.D=a==chrome.cast.ReceiverAvailability.AVAILABLE;z7(this)!=b&&this.V("yt-remote-cast2-availability-change",z7(this))}};
g.h.kH=function(){this.la()||(this.B=qFa(this),y7("Updating custom receivers: "+g.Ug(this.B)),chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(){this.tc("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",z7(this)))};
x7.prototype.setLaunchParams=x7.prototype.LV;x7.prototype.setConnectedScreenStatus=x7.prototype.KV;x7.prototype.stopSession=x7.prototype.OW;x7.prototype.getCastSession=x7.prototype.NW;x7.prototype.requestSession=x7.prototype.requestSession;x7.prototype.init=x7.prototype.init;x7.prototype.dispose=x7.prototype.dispose;var G7=[];g.h=L7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";M7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.Zf=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.A=a.seekableEnd,this.H=a.duration,this.J=a.loadedTime,this.B=a.liveIngestionTime,this.D=!isNaN(this.B))};
g.h.tb=function(){return 1==this.playerState};
g.h.isAdPlaying=function(){return 1081==this.playerState};
g.h.getDuration=function(){return this.D?this.H+N7(this):this.H};
g.h.clone=function(){return new L7(R7(this))};g.B(T7,g.V);g.h=T7.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.z,Z7(this,"play")):Y7(this,"play"),X7(this,1,P7(U7(this))),this.V("remotePlayerChange")):V7(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.z,Z7(this,"pause")):Y7(this,"pause"),X7(this,2,P7(U7(this))),this.V("remotePlayerChange")):V7(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.A){var b=U7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.tb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.z,Z7(this,"seekTo",{newTime:a}))}else Y7(this,"seekTo",{newTime:a});X7(this,3,a);this.V("remotePlayerChange")}else V7(this,g.La(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.z,Z7(this,"stopVideo")):Y7(this,"stopVideo");var a=U7(this);a.index=-1;a.videoId="";M7(a);W7(this,a);this.V("remotePlayerChange")}else V7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=U7(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.A)(function(){c7("CP","set receiver volume: "+d)},this),(0,g.A)(function(){this.tc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.A)(function(){c7("CP","set receiver muted: "+b)},this),(0,g.A)(function(){this.tc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);Y7(this,"setVolume",e)}c.muted=b;c.volume=a;W7(this,c)}else V7(this,g.La(this.setVolume,a,b))};
g.h.gG=function(a,b){if(1==this.o){var c=U7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Ug(b.style),g.ic(d,c.o));Y7(this,"setSubtitlesTrack",d);W7(this,c)}else V7(this,g.La(this.gG,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){Y7(this,"setAudioTrack",{videoId:a,audioTrackId:b.Ob.id});var c=U7(this);c.audioTrackId=b.Ob.id;W7(this,c)}else V7(this,g.La(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=U7(this);c=c||0;var m={videoId:a,currentIndex:c};Q7(l,a,c);g.za(b)&&(O7(l,b),m.currentTime=b);g.za(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Ug(k));Y7(this,"setPlaylist",m);d||W7(this,l)};
g.h.Lq=function(a,b){if(1==this.o){if(a&&b){var c=U7(this);Q7(c,a,b);W7(this,c)}Y7(this,"previous")}else V7(this,g.La(this.Lq,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=U7(this);Q7(c,a,b);W7(this,c)}Y7(this,"next")}else V7(this,g.La(this.nextVideo,a,b))};
g.h.OA=function(){1==this.o?Y7(this,"dismissAutoplay"):V7(this,this.OA)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.V("proxyStateChange",a,this.o)}T7.ga.dispose.call(this)};
g.h.W=function(){DFa(this);this.C=null;this.D.clear();S7(this,null);T7.ga.W.call(this)};
g.h.Fy=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.pD(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.jT=function(a,b){this.V(a,b)};
g.h.MQ=function(a){if(!a)this.zn(null),S7(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=U7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)c7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,W7(this,b)}};
g.h.zn=function(a){c7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),EFa(this),this.V("remotePlayerChange")};
g.h.LQ=function(a){a?(EFa(this),this.V("remotePlayerChange")):this.zn(null)};
g.h.Tx=function(){Y7(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.YQ=function(){var a=AFa();a&&S7(this,a)};
g.h.tc=function(a){c7("CP",a)};g.B($7,g.V);g.h=$7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.za(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.za(k)&&(l.currentIndex=k);c&&(this.qb.listId=c);this.qb.videoId=d;this.qb.index=k||0;this.qb.state=3;O7(this.qb,m);this.C="UNSUPPORTED";a8("Connecting with setPlaylist and params: "+g.Ug(l));this.o.connect({method:"setPlaylist",
params:g.Ug(l)},a,cEa())}else a8("Connecting without params"),this.o.connect({},a,cEa());GFa(this)};
g.h.dispose=function(){this.la()||(this.V("beforeDispose"),b8(this,3));$7.ga.dispose.call(this)};
g.h.W=function(){c8(this);e8(this);d8(this);g.SE(this.J);this.J=NaN;g.SE(this.K);this.K=NaN;this.B=null;g.EG(this.T);this.T.length=0;this.o.dispose();$7.ga.W.call(this);this.C=this.G=this.A=this.qb=this.o=null};
g.h.gL=function(){this.F(2)};
g.h.QQ=function(){a8("Channel opened");this.N&&(this.N=!1,d8(this),this.R=g.QE((0,g.A)(function(){a8("Timing out waiting for a screen.");this.F(1)},this),15E3));
gEa(QEa(this.o),this.aa)};
g.h.NQ=function(){a8("Channel closed");isNaN(this.D)?r6(!0):r6();this.dispose()};
g.h.OQ=function(a){r6();isNaN(this.H())?(a8("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,a8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),b8(this,2))};
g.h.PQ=function(a){a.params?a8("Received: action="+a.action+", params="+g.Ug(a.params)):a8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Xx(a.params.devices);this.A=(0,g.I)(a,function(a){return new f6(a)});
a=!!g.Qa(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
JFa(this,a);break;case "loungeScreenDisconnected":g.$a(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
JFa(this,!1);break;case "remoteConnected":var b=new f6(g.Xx(a.params.device));g.Qa(this.A,function(a){return b?a.id==b.id:!1})||g.Xa(this.A,b);
break;case "remoteDisconnected":b=new f6(g.Xx(a.params.device));g.$a(this.A,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":LFa(this,a);break;case "nowPlaying":NFa(this,a);break;case "onStateChange":MFa(this,a);break;case "onAdStateChange":OFa(this,a);break;case "onVolumeChanged":PFa(this,a);break;case "onSubtitlesTrackChanged":KFa(this,a);break;case "nowAutoplaying":QFa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.V("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.V("autoplayModeChange",this.C);"DISABLED"==this.C&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":RFa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:a8("Unrecognized action: "+a.action)}};
g.h.rV=function(){if(this.B){var a=this.B;this.B=null;this.qb.videoId!=a&&f8(this,"getNowPlaying")}};
$7.prototype.subscribe=$7.prototype.subscribe;$7.prototype.unsubscribeByKey=$7.prototype.Ak;$7.prototype.ha=function(){var a=3;this.la()||(a=0,isNaN(this.H())?Y6(this.o)&&isNaN(this.D)&&(a=1):a=2);return a};
$7.prototype.getProxyState=$7.prototype.ha;$7.prototype.F=function(a){a8("Disconnecting with "+a);c8(this);this.V("beforeDisconnect",a);1==a&&r6();REa(this.o,a);this.dispose()};
$7.prototype.disconnect=$7.prototype.F;$7.prototype.fa=function(){var a=this.qb;this.B&&(a=this.qb.clone(),Q7(a,this.B,a.index));return R7(a)};
$7.prototype.getPlayerContextData=$7.prototype.fa;
$7.prototype.ma=function(a){var b=new L7(a);b.videoId&&b.videoId!=this.qb.videoId&&(this.B=b.videoId,g.SE(this.J),this.J=g.QE((0,g.A)(this.rV,this),5E3));var c=[];this.qb.listId==b.listId&&this.qb.videoId==b.videoId&&this.qb.index==b.index||c.push("remoteQueueChange");this.qb.playerState==b.playerState&&this.qb.volume==b.volume&&this.qb.muted==b.muted&&P7(this.qb)==P7(b)&&g.Ug(this.qb.o)==g.Ug(b.o)||c.push("remotePlayerChange");this.qb.reset(a);(0,g.C)(c,function(a){this.V(a)},this)};
$7.prototype.setPlayerContextData=$7.prototype.ma;$7.prototype.Z=function(){var a=this.o.F.id,b=g.Qa(this.A,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
$7.prototype.getOtherConnectedRemoteId=$7.prototype.Z;$7.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.H)():NaN};
$7.prototype.getReconnectTimeout=$7.prototype.H;$7.prototype.ea=function(){return this.C||"UNSUPPORTED"};
$7.prototype.getAutoplayMode=$7.prototype.ea;$7.prototype.da=function(){return this.G||""};
$7.prototype.getAutoplayVideoId=$7.prototype.da;$7.prototype.ya=function(){if(!isNaN(this.H())){var a=this.o.A;g.bv(a.o);a.start()}};
$7.prototype.reconnect=$7.prototype.ya;$7.prototype.ka=function(a,b){f8(this,a,b);IFa(this)};
$7.prototype.sendMessage=$7.prototype.ka;g.B(g8,g7);g.h=g8.prototype;g.h.ze=function(a){return this.ld.$_gs(a)};
g.h.contains=function(a){return!!this.ld.$_c(a)};
g.h.get=function(a){return this.ld.$_g(a)};
g.h.start=function(){this.ld.$_st()};
g.h.add=function(a,b,c){this.ld.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.ld.$_r(a,b,c)};
g.h.Nr=function(a,b,c,d){this.ld.$_un(a,b,c,d)};
g.h.W=function(){for(var a=0,b=this.A.length;a<b;++a)this.ld.$_ubk(this.A[a]);this.A.length=0;this.ld=null;g8.ga.W.call(this)};
g.h.KW=function(){this.V("screenChange")};
g.h.IS=function(){this.V("onlineScreenChange")};
p7.prototype.$_st=p7.prototype.start;p7.prototype.$_gspc=p7.prototype.LW;p7.prototype.$_gsppc=p7.prototype.jH;p7.prototype.$_c=p7.prototype.contains;p7.prototype.$_g=p7.prototype.get;p7.prototype.$_a=p7.prototype.add;p7.prototype.$_un=p7.prototype.Nr;p7.prototype.$_r=p7.prototype.remove;p7.prototype.$_gs=p7.prototype.ze;p7.prototype.$_gos=p7.prototype.iH;p7.prototype.$_s=p7.prototype.subscribe;p7.prototype.$_ubk=p7.prototype.Ak;var h8=null,i8=null,x8=null,m8=[];g.r(y8,g.J);g.h=y8.prototype;
g.h.W=function(){g.J.prototype.W.call(this);this.C.stop();this.F.stop();this.L.stop();this.N();this.o.unsubscribe("proxyStateChange",this.RE,this);this.o.unsubscribe("remotePlayerChange",this.Cn,this);this.o.unsubscribe("remoteQueueChange",this.Gq,this);this.o.unsubscribe("autoplayUpNext",this.oE,this);this.o.unsubscribe("previousNextChange",this.OE,this);this.o.unsubscribe("nowAutoplaying",this.GE,this);this.o.unsubscribe("autoplayDismissed",this.nE,this);this.o=this.D=null};
g.h.qD=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(B8(this)){if(!U7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":U7(this.o).tb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.K.Cm(c[0],c[1]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.o.setAudioTrack(this.A.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.A.getCurrentTime();D8(this,0==c?void 0:c);break;case "control_seek":D8(this,c[0]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.o.setAudioTrack(this.A.getVideoData(1).videoId,c)}};
g.h.KQ=function(a){this.L.bL(a)};
g.h.mW=function(a){this.qD("control_subtitles_set_track",g.ac(a)?null:a)};
g.h.wG=function(){var a=this.A.getOption("captions","track");g.ac(a)||C8(this,a)};
g.h.CE=function(a){if(B8(this)){this.o.unsubscribe("remotePlayerChange",this.Cn,this);var b=Math.round(a.volume);a=!!a.muted;var c=U7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.R.start();this.o.subscribe("remotePlayerChange",this.Cn,this)}};
g.h.cS=function(){g.ac(this.G)||cGa(this,this.G);this.H=!1};
g.h.RE=function(a,b){this.F.stop();2==b&&this.uG()};
g.h.Cn=function(){if(B8(this)){this.C.stop();var a=U7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.D.Yk(1);break;case 1082:case 1083:this.D.Yk(0);break;default:this.D.Yk(-1)}switch(a.playerState){case 1081:case 1:A8(this,new g.MQ(8));this.tG();break;case 1085:case 3:A8(this,new g.MQ(9));break;case 1083:case 0:A8(this,new g.MQ(2));this.K.stop();z8(this,this.A.getVideoData().lengthSeconds);break;case 1084:A8(this,new g.MQ(4));break;case 2:A8(this,new g.MQ(4));z8(this,P7(a));
break;case -1:A8(this,new g.MQ(64));break;case -1E3:A8(this,new g.MQ(128,{errorCode:"mdx.remoteerror",message:"Este v\u00eddeo no se puede reproducir de forma remota."}))}a=U7(this.o).o;var b=this.G;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.G=a,cGa(this,a));a=U7(this.o);-1==a.volume||Math.round(this.A.getVolume())==a.volume&&this.A.isMuted()==a.muted||this.R.isActive()||this.WG()}else bGa(this)};
g.h.OE=function(){this.A.V("mdxpreviousnextchange")};
g.h.Gq=function(){B8(this)||bGa(this)};
g.h.cK=function(){this.o.OA()};
g.h.oE=function(a){a&&(a=g.BF("/watch_queue_ajax",{method:"GET",gd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.A)(this.rU,this)}))&&(this.N=(0,g.A)(a.abort,a))};
g.h.rU=function(a,b){var c=new g.GP(g.Y(this.A),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.A.V("mdxautoplayupnext",c)};
g.h.GE=function(a){isNaN(a)||this.A.V("mdxnowautoplaying",a)};
g.h.nE=function(){this.A.V("mdxautoplaycanceled")};
g.h.EO=function(a,b){-1==U7(this.o).playerState?D8(this,a):b&&this.o.seekTo(a)};
g.h.WG=function(){if(B8(this)){var a=U7(this.o);this.B.La(this.T);a.muted?this.A.mute():this.A.unMute();this.A.setVolume(a.volume);this.T=this.B.O(this.A,"onVolumeChange",this.CE)}};
g.h.tG=function(){this.C.stop();if(!this.o.la()){var a=U7(this.o);a.tb()&&A8(this,new g.MQ(8));z8(this,P7(a));this.C.start()}};
g.h.uG=function(){this.F.stop();this.C.stop();var a=this.o.C.getReconnectTimeout();2==this.o.o&&!isNaN(a)&&this.F.start()};g.r(E8,g.W);E8.prototype.D=function(a){eGa(this,a.state)};g.r(F8,g.cX);F8.prototype.L=function(){var a=this.B.getOption("remote","receivers");a&&1<a.length&&!this.B.getOption("remote","quickCast")?(this.H=g.sb(a,this.F,this),g.dX(this,(0,g.I)(a,this.F)),a=this.B.getOption("remote","currentReceiver"),this.Af(this.F(a)),this.enable(!0)):this.enable(!1)};
F8.prototype.F=function(a){return a.key};
F8.prototype.zf=function(a){return"cast-selector-receiver"==a?"Reparto...":this.H[a].name};
F8.prototype.Id=function(a){g.cX.prototype.Id.call(this,a);this.B.setOption("remote","currentReceiver",this.H[a]);this.C.Kb()};g.r(G8,g.oV);g.h=G8.prototype;g.h.create=function(){WFa(g.wN(g.Y(this.player)));this.D.push(g.XE("yt-remote-before-disconnect",this.GQ,this));this.D.push(g.XE("yt-remote-connection-change",this.tT,this));this.D.push(g.XE("yt-remote-receiver-availability-change",this.PE,this));this.D.push(g.XE("yt-remote-auto-connect",this.rT,this));this.D.push(g.XE("yt-remote-receiver-resumed",this.qT,this));this.PE()};
g.h.load=function(){this.player.cancelPlayback();g.oV.prototype.load.call(this);this.C=new y8(this,this.player,this.o);var a=(a=aGa())?a.currentTime:0;var b=w8()?new T7(r8(),void 0):null;0==a&&b&&(a=P7(U7(b)));0!=a&&this.Je(a);dGa(this,this.kn,this.kn);g.D0(this.player.app,6)};
g.h.unload=function(){this.player.V("mdxautoplaycanceled");this.B=this.A;g.Bf(this.C,this.o);this.o=this.C=null;g.oV.prototype.unload.call(this);g.D0(this.player.app,5)};
g.h.W=function(){g.YE(this.D);g.oV.prototype.W.call(this)};
g.h.Yh=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.qD.apply(this.C,[a].concat(g.ea(c)))};
g.h.Yk=function(a){this.H=a};
g.h.getAdState=function(){return this.H};
g.h.VK=function(){return this.loaded?this.C.suggestion:null};
g.h.Zf=function(){return this.o?U7(this.o).Zf:!1};
g.h.hasNext=function(){return this.o?U7(this.o).hasNext:!1};
g.h.Je=function(a,b){this.J=a||0;this.player.V("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.J};
g.h.getProgressState=function(){var a=U7(this.o),b=this.player.getVideoData();return{allowSeeking:g.Y(this.player).experiments.o("web_player_mdx_allow_seeking_change_killswitch")?this.player.Nc():!a.isAdPlaying()&&this.player.Nc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.D?a.B+N7(a):a.B,isPeggedToLive:1>=(a.D?a.A+N7(a):a.A)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.D?a.A+N7(a):a.A,seekableStart:0<a.C?a.C+
N7(a):a.C}};
g.h.nextVideo=function(){this.o&&this.o.nextVideo()};
g.h.Lq=function(){this.o&&this.o.Lq()};
g.h.GQ=function(a){1==a&&(this.G=this.o?U7(this.o):null)};
g.h.tT=function(){var a=w8()?new T7(r8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.G=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Af(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.G)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,P7(a)));this.player.V("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.PE=function(){this.F=[this.A].concat(YFa());var a=s8()||this.A;H8(this,a);this.player.Ba("onMdxReceiversChange")};
g.h.rT=function(){var a=s8();H8(this,a)};
g.h.qT=function(){this.B=s8()};
g.h.Jc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?J7():H8(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&J7(),!0):!1}};
g.h.Tx=function(){this.o.Tx()};
g.h.wc=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.WZ.remote=G8;})(_yt_player);
